apiVersion: v1
kind: Service
metadata:
  name: liatrio-exercist-service
  namespace: liatrio-main-ns
  labels:
    app: liatrio-exercist-app
spec:
  selector:
    app: liatrio-exercist-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
